export const EXAM_ANALYSIS = 'App/Chart/EXAM_ANALYSIS';
export const EXAM_ANALYSIS_SUCCESS = 'App/Chart/EXAM_ANALYSIS_SUCCESS';
export const EXAM_ANALYSIS_ERROR = 'App/Chart/EXAM_ANALYSIS_ERROR';

export const PRACTICE_ANALYSIS = 'App/Chart/PRACTICE_ANALYSIS';
export const PRACTICE_ANALYSIS_SUCCESS = 'App/Chart/PRACTICE_ANALYSIS_SUCCESS';
export const PRACTICE_ANALYSIS_ERROR = 'App/Chart/PRACTICE_ANALYSIS_ERROR';

