export const LOAD_SHOP_DETAIL = 'App/Shop/LOAD_SHOP_DETAIL';
export const LOAD_SHOP_DETAIL_SUCCESS = 'App/Shop/LOAD_SHOP_DETAIL_SUCCESS';
export const LOAD_SHOP_DETAIL_ERROR = 'App/Shop/LOAD_SHOP_DETAIL_ERROR';
