export const QUERY_FIRST_CATEGORY = 'App/Category/QUERY_FIRST_CATEGORY';
export const QUERY_FIRST_CATEGORY_SUCCESS = 'App/Category/QUERY_FIRST_CATEGORY_SUCCESS';
export const QUERY_FIRST_CATEGORY_ERROR = 'App/Category/QUERY_FIRST_CATEGORY_ERROR';

export const QUERY_SECOND_CATEGORY = 'App/Category/QUERY_SECOND_CATEGORY';
export const QUERY_SECOND_CATEGORY_SUCCESS = 'App/Category/QUERY_SECOND_CATEGORY_SUCCESS';
export const QUERY_SECOND_CATEGORY_ERROR = 'App/Category/QUERY_SECOND_CATEGORY_ERROR';


export const QUERY_THIRD_CATEGORY = 'App/Category/QUERY_THIRD_CATEGORY';
export const QUERY_THIRD_CATEGORY_SUCCESS = 'App/Category/QUERY_THIRD_CATEGORY_SUCCESS';
export const QUERY_THIRD_CATEGORY_ERROR = 'App/Category/QUERY_THIRD_CATEGORY_ERROR';

export const QUERY_FOURTH_CATEGORY = 'App/Category/QUERY_FOURTH_CATEGORY';
export const QUERY_FOURTH_CATEGORY_SUCCESS = 'App/Category/QUERY_FOURTH_CATEGORY_SUCCESS';
export const QUERY_FOURTH_CATEGORY_ERROR = 'App/Category/QUERY_FOURTH_CATEGORY_ERROR';


